spring.datasource.url=jdbc:sqlserver://${MSSQL_HOST:localhost}:1433;databaseName=${MSSQL_DB:SmartTask};encrypt=true;trustServerCertificate=false
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=${MSSQL_USER:sa}
spring.datasource.password=${MSSQL_PASSWORD}
spring.datasource.hikari.maximum-pool-size=10
spring.sql.init.mode=never
