spring.datasource.url=jdbc:oracle:thin:@//${ORACLE_HOST:localhost}:1521/${ORACLE_SERVICE:SMARTTASK}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=${ORACLE_USER:smarttask}
spring.datasource.password=${ORACLE_PASSWORD}
spring.datasource.hikari.maximum-pool-size=10
spring.sql.init.mode=never
